### ISSUE TITLE
[BUG 11] : Counter mismatch due to undo deleted test step

### ISSUE THREAD

**Issue by montbaga** [katalon-studio/Cloud-Studio#11]
**To Reproduce**
1. Create a test case , lets say with three test steps.
2. Delete any one test step and click Run and immediately undo the test step making it the 3rd step test case again
3. The test case will not execute the "undo" test step but will take the "undo" test steps in the counters.

This might be interconnected with the bug number  #10 

**Expected behavior**

**Screenshots**
![image](https://github.com/katalon-studio/cloud-studio/assets/64852258/f1a999a9-7b3b-4972-a614-cb84ef0ce3d0)

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser chrome and edge

**Additional context**
*Add any other context about the problem here.*

**Comment by vyhuynhthanh** [comment]
Hi @montbaga, thanks a lot for logging this issue. We'll be looking into it.

**Comment by montbaga** [comment]
Retested and working fine. Closing this defect @vyhuynhthanh
