### ISSUE TITLE
[BUG]: While editing the recorded script, by replacing the existing 'Click' action with Verification of element, the help text is overlaying the actual actions available for Verification. 

### ISSUE THREAD

**Issue by ravikaanthe** [katalon-studio/Cloud-Studio#12]
**To Reproduce**
1. Create any test case with some test steps
2. Now try to edit any test step

**Expected behavior**
The help text of 'Click' action should not be overlapped with the actual 'verification actoins' options.

**Screenshots**
![Katalon Clod - Bug 1](https://github.com/katalon-studio/cloud-studio/assets/32113787/ca8ca60f-69c6-41b5-8a0a-7a8fd53793c5)

**Comment by vyhuynhthanh** [comment]
Many thanks @ravikaanthe for noting this bug, we already noted this bug and will fix this in the next release.

**Comment by vyhuynhthanh** [comment]
Hi @ravikaanthe,

The bug you reported has been resolved. Please retest and inform us if you encounter any other issues. You can find detailed information about this release in our release notes available [here](https://docs.katalon.com/docs/release-notes/katalon-cloud-studio/katalon-cloud-studio-beta-release#beta---august-21-2023).

Thank you.
