### ISSUE TITLE
[BUG]: Floating menu is missing and unable to capture new object while editing the existing test step 

### ISSUE THREAD

**Issue by ravikaanthe** [katalon-studio/Cloud-Studio#13]
**To Reproduce**
1.  Create a test case  by using record option.
2. Now click on 'Edit' option for any test case.
3. Now select 'Object' Dropdown to "Capture New Object"
4. Click on "Capture New Object"
5. Opens your application URL and user navigated to System under test application
6. Now click the object that you would like to capture.

**Expected behavior**
Floating menu should display, so that user can click on 'Save' to finish capturing the new object

Actual behavior:
Upon clicking the object that would like to capture, the application is getting steered and Floating menu is missing.

**Screenshots**
![Katalon Clod - Bug 2](https://github.com/katalon-studio/cloud-studio/assets/32113787/1617c864-4d38-4d92-adf2-67b0c8f0313a)

![Katalon Clod - Bug 2-1](https://github.com/katalon-studio/cloud-studio/assets/32113787/7aab5a17-9c8d-43ed-aa1f-221bfe8ca030)

**Comment by vyhuynhthanh** [comment]
Hi @ravikaanthe ravi

Thanks a lot for logging this issue. Based on the image, it looks like the application URL is https://demowebshop.tricentis.com/?

We have already logged this issue and will work on addressing it for the next release.

Best.
Vy

**Comment by vyhuynhthanh** [comment]
Hi @ravikaanthe, 

The bug you reported has been resolved. Please retest and inform us if you encounter any other issues. You can find detailed information about this release in our release notes available [here](https://docs.katalon.com/docs/release-notes/katalon-cloud-studio/katalon-cloud-studio-beta-release#beta---august-21-2023).

Thank you.
