### ISSUE TITLE
[BUG] - Unable to escape from new Object Capturing, if user decide to not capture the new object.

### ISSUE THREAD

**Issue by ravikaanthe** [katalon-studio/Cloud-Studio#24]
**To Reproduce**
1. Record a new test for end to end scenario
2. Now manually "Add New Test Step" and select "Create New Object"
3. The user will be navigated to the Web Browser with application URL
4. Now user decide to not capture the new object on same page of application. User is unable to escape from new object capturing session by keeping the existing application state as it is

**Expected behavior**
*User should be able to escape/cancel from new Object Capturing, if user decide to not capture the new object by keeping the existing application state as it is.

**Screenshots**
![image](https://github.com/katalon-studio/cloud-studio/assets/32113787/1fc6803c-053e-4df7-ae62-df7e890d10f5)

**Desktop (please complete the following information):**

**Additional context**
*Add any other context about the problem here.*

**Comment by vyhuynhthanh** [comment]
Hi Ravi, this issue is related to this one https://github.com/katalon-studio/cloud-studio/issues/13 and we are fixing this, thank you for letting us know 🤝
