### ISSUE TITLE
[BUG 4] : Commands like Get Url does not seem significant in the test steps

### ISSUE THREAD

**Issue by montbaga** [katalon-studio/Cloud-Studio#4]
**To Reproduce**
1. Create a test step and use the commands like "Get Url". The test step while running the test step may get passed but.. 
2. How would the user verify that that get url as there is no code option which can be used to store this in  a variable

**Expected behavior**
*if this command is a feature in Cloud Studio then there should also be something to store and verify it.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser Chrome

**Additional context**
*Add any other context about the problem here.*

**Comment by montbaga** [comment]
Invalid bug

**Comment by montbaga** [comment]
how to verify this with expected url

**Comment by Padoplin** [comment]
Hi @montbaga 

Appreciate your enthusiasm. To compare the URL you get with the expected URL, we will provide "Verify if <String> matches the expected <String> " in upcoming releases. 

Meanwhile, please keep your feedback coming up.

Best Regards, 
Jass

**Comment by vyhuynhthanh** [comment]
Hi @montbaga,

I'd like to inform you that in the most recent release, we have introduced a new keyword called "Verify if URL matches the expected URL." This keyword allows you to check if a URL matches the expected URL. For detailed information, please refer to our release note [here](https://docs.katalon.com/docs/release-notes/katalon-cloud-studio/katalon-cloud-studio-beta-release#beta---september-20-2023).

Thank you

**Comment by montbaga** [comment]
Hello @vyhuynhthanh : Retested and working fine at my end. Thanks a lot for adding this.
